//! Type registry mapping DDS type names to TypeDescriptionMsg.
//!
//! Uses a compile-time `phf::Map` generated by `build.rs` from ROS2 `.msg` files.
//! Each entry maps a DDS type name (e.g. `"std_msgs::msg::dds_::String_"`) to a
//! JSON-serialized `TypeDescriptionMsg` that is deserialized on first lookup.

use ros2_types::types::TypeDescriptionMsg;
use std::collections::HashMap;
use std::sync::LazyLock;

// Include the phf::Map generated by build.rs
include!(concat!(env!("OUT_DIR"), "/type_registry.rs"));

/// Deserialized cache — lazily populated from the phf JSON strings.
static CACHE: LazyLock<HashMap<&'static str, TypeDescriptionMsg>> = LazyLock::new(|| {
    let mut map = HashMap::with_capacity(REGISTRY.len());
    for (key, json) in REGISTRY.entries() {
        if let Ok(desc) = serde_json::from_str::<TypeDescriptionMsg>(json) {
            map.insert(*key, desc);
        }
    }
    map
});

/// Look up a type description by DDS type name.
///
/// DDS names look like: `"std_msgs::msg::dds_::String_"`
pub fn lookup_dds(dds_name: &str) -> Option<&'static TypeDescriptionMsg> {
    CACHE.get(dds_name)
}
